; PlatformIO Project Configuration File
;
;   OllO RP2040 + ESP32-S3 firmware

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
build_src_filter = +<*> -<Esp32_main.cpp>
lib_deps =
    https://github.com/adafruit/PicoDVI.git
    adafruit/Adafruit GFX Library
    https://github.com/lvgl/lvgl.git#v9.6.0
lib_ignore =
    SdFat - Adafruit Fork
    SD
    SDFS
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Your Super Mini has 4 MB flash
board_upload.flash_size = 4MB
board_build.partitions = default.csv

; Only compile the ESP32 code
build_src_filter =
    +<Esp32_main.cpp>
    -<Rp2040_main.cpp>

; BLE
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.1
